# Generated by Django 4.2.1 on 2023-05-13 16:31

from django.db import migrations

def populate_roles(apps, schemaeditor):
    roles = {
        "zookeeper": "They may feed animals, clean and groom them, and prepare their diets. ",
        "veterinarian": "They are animal health care professionals who help maintain animal health through preventative care and medical intervention.",
        "agent": "They work in a client-facing role and manage guest experiences. "
    }
    Roles = apps.get_model("accounts", "Role")
    for key, value in roles.items():
        role = Roles(name=key, description=value)
        role.save()

def populate_departments(apps, schemaeditor):
    departments = {
        "education": "They manage volunteer programs.",
        "guest services": "They handle the visitants experience",
        "medical attention": "Group of specialist that manage the health of animals"
    }
    Departments = apps.get_model("accounts", "Department")
    for key, value in departments.items():
        dept = Departments(name=key, description=value)
        dept.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_departments),
        migrations.RunPython(populate_roles)
    ]
